# Generated by Django 4.1.2 on 2022-11-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solditem',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='solditem',
            old_name='item_id',
            new_name='item',
        ),
    ]
