# Generated by Django 4.1.2 on 2022-11-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_buyer_id_solditem_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='contact',
            field=models.CharField(max_length=60),
        ),
        migrations.RemoveField(
            model_name='item',
            name='seller_id',
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact',
            field=models.CharField(max_length=60),
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.seller'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.buyer'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.item'),
        ),
    ]
