# Generated by Django 4.1.2 on 2022-11-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_buyer_contact_remove_item_seller_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='item',
            name='seller_id',
            field=models.ManyToManyField(null=True, to='content.seller'),
        ),
    ]
