# Generated by Django 4.1.2 on 2022-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_item_seller_id_item_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller_id',
            field=models.ManyToManyField(blank=True, to='content.seller'),
        ),
    ]
